### ISSUE TITLE
renew

### ISSUE THREAD

**Issue by martunta** [afgallo/flynn-ssl-cert#2]
what do you think would be best way how to set up automatic renewal after certs are installed for the first time?

**Comment by afgallo** [comment]
Good question, haven't done that yet. But maybe create a Flynn app (worker) that runs a timer which checks whether the cert needs to be renewed?

**Comment by martunta** [comment]
It would be fine to run certbot every night on auto I think, and then it would work only when renewalnis actually due. But I am not sure how to make that as a worker task

**Comment by afgallo** [comment]
You could potentially just write a bash script that runs on an interval and deploy that to Flynn as a worker or clock type of app.

https://stackoverflow.com/questions/6583784/linux-command-to-run-script-at-intervals

https://askubuntu.com/questions/430382/repeat-a-command-every-x-interval-of-time-in-terminal

**Comment by nrempel** [comment]
Hi @martunta, I built a tool to do this (running on the Flynn cluster directly). I wanted to share since I came across this thread before building it myself.

https://github.com/nrempel/flynn-certbot

**Comment by martunta** [comment]
I have been using https://github.com/afgallo/flynn-ssl-cert

it was working quite nice, although there was no way to automate it and I had to remember running it every 3 months. Also it did not support having several routes with different domains for one app, so I had to modify it. 

If your script runs directly on cluster, then it is a step up
